modify deploy

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -17,7 +17,7 @@ jobs:
       POSTGRES_DB: ${{ vars.POSTGRES_DB }}
       POSTGRES_PORT: ${{ vars.POSTGRES_PORT }}
       APP_PORT: ${{ vars.APP_PORT }}
-      ENV: ${{ vars.ENV }}
+      ENV: ${{ github.ref_name == 'main' && 'prod' || 'test' }}
 
     steps:
       - name: Checkout repo
@@ -31,20 +31,21 @@ jobs:
             up -d --build --remove-orphans
 
       - name: Connect App container to proxy network
-        run: |
-          CONTAINER_ID=$(docker compose -f docker-compose.base.yml -f docker-compose.${ENV}.yml ps -q app)
-          PROXY_NET=nathan_default
-          if [ -n "$CONTAINER_ID" ]; then
-            if ! docker network inspect ${PROXY_NET} | grep -q "$CONTAINER_ID"; then
-              docker network connect ${PROXY_NET} "$CONTAINER_ID"
-              echo "Connected container to ${PROXY_NET}"
-            else
-              echo "Container already connected to ${PROXY_NET}"
-            fi
-          else
-            echo "App container not found"
-            exit 1
-          fi
+        run: docker network connect nathan_default hangman-${ENV}
+
+          # CONTAINER_ID=$(docker compose -f docker-compose.base.yml -f docker-compose.${ENV}.yml ps -q app)
+          # PROXY_NET=nathan_default
+          # if [ -n "$CONTAINER_ID" ]; then
+          #   if ! docker network inspect ${PROXY_NET} | grep -q "$CONTAINER_ID"; then
+          #     docker network connect ${PROXY_NET} "$CONTAINER_ID"
+          #     echo "Connected container to ${PROXY_NET}"
+          #   else
+          #     echo "Container already connected to ${PROXY_NET}"
+          #   fi
+          # else
+          #   echo "App container not found"
+          #   exit 1
+          # fi
 
       - name: Cleanup unused images
         run: docker image prune -f
