better script to add container to proxy network [no ci]

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -35,21 +35,20 @@ jobs:
             up -d --build --remove-orphans
 
       - name: Connect App container to proxy network
-        run: docker network connect nathan_default hangman-${ENV}
-
-          # CONTAINER_ID=$(docker compose -f docker-compose.base.yml -f docker-compose.${ENV}.yml ps -q app)
-          # PROXY_NET=nathan_default
-          # if [ -n "$CONTAINER_ID" ]; then
-          #   if ! docker network inspect ${PROXY_NET} | grep -q "$CONTAINER_ID"; then
-          #     docker network connect ${PROXY_NET} "$CONTAINER_ID"
-          #     echo "Connected container to ${PROXY_NET}"
-          #   else
-          #     echo "Container already connected to ${PROXY_NET}"
-          #   fi
-          # else
-          #   echo "App container not found"
-          #   exit 1
-          # fi
+        run: |
+          CONTAINER_ID=$(docker compose -f docker-compose.base.yml -f docker-compose.${ENV}.yml ps -q app)
+          PROXY_NET=nathan_default
+          if [ -n "$CONTAINER_ID" ]; then
+            if ! docker network inspect ${PROXY_NET} | grep -q "$CONTAINER_ID"; then
+              docker network connect ${PROXY_NET} "$CONTAINER_ID"
+              echo "Connected container to ${PROXY_NET}"
+            else
+              echo "Container already connected to ${PROXY_NET}"
+            fi
+          else
+            echo "App container not found"
+            exit 1
+          fi
 
       - name: Cleanup unused images
         run: docker image prune -f
